---
title: "Untitled"
format: html
---

```{r}
#| label: setup

LoadPackages(rvest, httr2, readxl, tidyr, dplyr, stringr, purrr)
```

```{r}
u <- 'https://www.sqa.org.uk/sqa/'
s <- rvest::session(u)

att_stat_data_paths <- s |>
    rvest::session_jump_to('105123.11712.html') |> 
    rvest::html_elements('a') |> 
    rvest::html_attr('href') |> 
    grepv('xlsx$', x = _)

att_stat_2025 <- grepv('2025', att_stat_data_paths)
sub('.*\\d\\d\\d\\d-', '', att_stat_2025)

download.file(file.path(u, att_stat_2025[[28]]), 'nat_5.xlsx', mode = 'wb')
```


```{r}
nat_5_toc <- read_xlsx(
    'nat_5.xlsx',
    sheet = 'Contents',
    range = 'A2:A34'
) |> 
    rename(toc = 1)



ea_lookup <- nat_5_toc |>
    separate_wider_regex(
        cols = 'toc',
        patterns = c('.+ ',
                     table = '\\d+', ':.+ - ',
                     desc = '.+')
    ) |> 
        mutate(table = paste0('EA', table), .after = 1)


all_att_data <- map(ea_lookup$table, ~{
    read_xlsx('nat_5.xlsx', sheet = .x, skip = 3) |>
        select(Subject, contains('Percent')) |> 
        mutate(
            across(everything(), ~trimws(sub('%|,', '', .))),
            across(-Subject, ~replace_values(., c('[c]', '[z]', '') ~ NA)),
            across(-Subject, as.numeric)
        )
}) |> 
    list_rbind() |> 
    View()

object.size(all_att_data)

z <- read_xlsx('nat_5.xlsx', sheet = 2, skip = 3)
unique(z[[1]])


summarize(z, across(contains('Count'), min))

```


```{r}

subjects_counts_2025 <- read_xlsx('nat_5.xlsx', sheet = 'EA1', skip = 3) |> 
    mutate(
        across(contains('Percent'), ~sub('%', '', .)),
        across(-1, as.numeric)
    ) |> 
    select(1, contains('Count')) |> 
    rowwise() |>   
    transmute(
        Subject,
        total_count = sum(c_across(2:36), na.rm = TRUE)
    ) |> 
    arrange(desc(total_count))

reframe(Subject, across(where(is.numeric), ~min(., na.rm = T)))


```